apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-01-backend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode-01-backend
  template:
    metadata:
      labels:
        app: episode-01-backend
    spec:
      containers:
      - name: backend
        image: hamayal/episode-01-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: episode-01-backend-service
  namespace: development
spec:
  selector:
    app: episode-01-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
