apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-02-backend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode-02-backend
  template:
    metadata:
      labels:
        app: episode-02-backend
    spec:
            containers:
             - name: backend
               image: episode-02-backend:latest
               ports:
                - containerPort: 5000
               resources:
                 limits:
                   cpu: 500m
                   memory: 512Mi
                 requests:
                   cpu: 200m
                   memory: 256Mi
    apiVersion: 
      kind: 
      metadata:
        name: episode-02-backend-service
        namespace: development
      
