apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-02-frontend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode-02-frontend
  template:
    metadata:
      labels:
        app: episode-02-frontend
    spec:
      containers:
      - name: frontend
        image: hamayal/episode-02-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: episode-02-frontend-service
  namespace: development
spec:
  selector:
    app: episode-02-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
