apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-04-frontend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode-04-frontend
  template:
    metadata:
      labels:
        app: episode-04-frontend
    spec:
            containers:
             - name: frontend
               image: hamayal/episode-04-frontend:latest
               ports:
               - containerPort: 3000
               resources:
                 limits:
                   cpu: "0.5"
                   memory: "512Mi"
                 requests:
                   cpu: "0.1"
                   memory: "256Mi"

    apiVersion: 
      kind: 
      metadata:
      name: episode-04-frontend-service
      namespace: development

